/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cn.stylefeng.java-conventions")
}

dependencies {
    implementation(project(":guns-system"))
    implementation(project(":guns-core"))
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

description = "guns-main"
