/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

group = "me.zhengjie"
version = "0.0.1"

dependencies {
    implementation(project(":eladmin-logging"))
    implementation(project(":eladmin-common"))
    implementation("javax.mail:mail:1.4.7")
    implementation("com.qiniu:qiniu-java-sdk:7.9.1")
    implementation("com.alipay.sdk:alipay-sdk-java:4.22.0.ALL")
}


