/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "2.7.3"
    id("io.spring.dependency-management") version "1.0.13.RELEASE"
    kotlin("jvm") version "1.7.10"
    kotlin("plugin.spring") version "1.7.10"
}




dependencies {
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("com.alibaba:fastjson:2.0.3")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("joda-time:joda-time:2.10.14")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.11")
    implementation("cn.hutool:hutool-all:5.8.6")
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.2")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    runtimeOnly("org.postgresql:postgresql:42.4.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

group = "com.kuang"
version = "0.0.1"
description = "Study"
java.sourceCompatibility = JavaVersion.VERSION_17



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
repositories {
    mavenCentral()
}
