/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "eladmin-kt"
include(":eladmin-generator")
include(":eladmin-logging")
include(":eladmin-system")
include(":eladmin-tools")
include(":eladmin-common")
