/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cn.stylefeng.java-conventions")
}

dependencies {
    implementation(project(":guns-core"))
    implementation("io.pebbletemplates:pebble:3.1.5")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("com.auth0:java-jwt:3.19.2")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.9")
    implementation("cn.stylefeng.roses:file-spring-boot-starter:7.2.2")
    implementation("cn.stylefeng.roses:sms-spring-boot-starter:7.2.2")
    implementation("com.aliyun:aliyun-java-sdk-core:4.6.0")
    implementation("com.aliyun:aliyun-java-sdk-ecs:4.24.18")
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("org.springframework.boot:spring-boot-starter-mail")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

description = "guns-system"
