/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.javaboy.java-conventions")
}

dependencies {
    implementation(project(":vhr-model"))
    implementation("com.auth0:java-jwt:3.19.2")
    implementation("org.springframework.boot:spring-boot-starter-aop:2.7.0")
}

description = "vhr-system"
