/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "guns-separation"
include(":guns-core")
include(":guns-system")
include(":guns-main")
