/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */


dependencies {
    implementation(project(":eladmin-common"))
    implementation("org.springframework.boot:spring-boot-starter-freemarker:2.7.0")
    implementation("org.apache.commons:commons-configuration2:2.7")
}


