/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "2.7.3"
    id("io.spring.dependency-management") version "1.0.13.RELEASE"
    kotlin("jvm") version "1.7.10"
    kotlin("plugin.spring") version "1.7.10"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-freemarker")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.2")
    implementation("org.springframework.boot:spring-boot-starter-aop")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
     implementation("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.apache.shiro:shiro-spring-boot-web-starter:1.9.0")
    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation("com.google.guava:guava:31.1-jre")

    implementation("com.auth0:java-jwt:4.0.0")
    implementation("org.apache.tika:tika-core:1.27")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("commons-logging:commons-logging:1.2")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("com.alibaba:fastjson:1.2.80")
    implementation("com.alibaba:druid-spring-boot-starter:1.2.9")
    implementation("org.springframework.boot:spring-boot-starter-mail")
    implementation("com.baidu.aip:java-sdk:4.16.7"){
        exclude(group = "org.slf4j", module = "slf4j-simple")

    }
    implementation("net.coobird:thumbnailator:0.4.17")
    implementation("cn.hutool:hutool-all:5.8.6")
    implementation("org.quartz-scheduler:quartz:2.3.2")
    implementation("com.netease.cloud:nos-sdk-java-publiccloud:1.3.1")
    implementation("org.springdoc:springdoc-openapi-ui:1.6.11")
    implementation("com.aliyun.oss:aliyun-sdk-oss:3.15.0")
    implementation("javax.xml.bind:jaxb-api:2.4.0-b180830.0359")
    implementation("org.glassfish.jaxb:jaxb-runtime:2.3.4")
    implementation("com.upyun:java-sdk:4.2.3")
    implementation("org.apache.commons:commons-text:1.9")
    implementation("com.qiniu:qiniu-java-sdk:7.10.2")
    implementation("com.qcloud:cos_api:5.6.80")
    implementation("commons-net:commons-net:3.8.0")
    runtimeOnly("org.postgresql:postgresql:42.4.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

group = "cn.hellohao"
version = "2.0.1"
description = "Tbed"
java.sourceCompatibility = JavaVersion.VERSION_17


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
repositories {
    mavenCentral()
}
