/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */


dependencies {
    implementation(project(":eladmin-generator"))
    implementation(project(":eladmin-tools"))
    implementation(project(":eladmin-common"))
    implementation(project(":eladmin-logging"))
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.quartz-scheduler:quartz:2.3.2")
    implementation("ch.ethz.ganymed:ganymed-ssh2:262")
    implementation("com.jcraft:jsch:0.1.55")
    implementation("com.github.oshi:oshi-core:5.8.6")
}


