/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.springframework.boot") version "2.7.3"
    id("io.spring.dependency-management") version "1.0.13.RELEASE"
    kotlin("jvm") version "1.7.10"
    kotlin("plugin.spring") version "1.7.10"
}

dependencies {
    implementation("com.baomidou:mybatis-plus-boot-starter:3.5.2")
    implementation("org.springframework.boot:spring-boot-starter-security:2.7.3")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.3")
    implementation("commons-codec:commons-codec:1.15")
    implementation("mysql:mysql-connector-java:8.0.30")
    implementation("commons-io:commons-io:2.11.0")
    implementation("com.alibaba:druid:1.2.12")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("aopalliance:aopalliance:1.0")
    compileOnly ("org.projectlombok:lombok:1.18.24")
    annotationProcessor ("org.projectlombok:lombok:1.18.24")
    implementation("cn.hutool:hutool-all:5.8.6")
}

group = "org.sang"
version = "0.0.1"
description = "blogserver"
java.sourceCompatibility = JavaVersion.VERSION_17



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
repositories {
    mavenCentral()
}
