/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
repositories {
    mavenCentral()
}



dependencies {
    implementation("cn.hutool:hutool-all")

    implementation("org.springdoc:springdoc-openapi-ui:1.6.11")

    implementation("commons-codec:commons-codec")
}

