/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "vhr"
include(":vhr-system")
include(":vhr-model")
include(":mailserver")
include(":vhrserver")
project(":vhr-system").projectDir = file("vhrserver/vhr-system")
project(":vhr-model").projectDir = file("vhrserver/vhr-model")
