/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.javaboy.java-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-amqp:2.7.0")
    implementation("org.springframework.boot:spring-boot-starter-data-redis:2.7.0")
    implementation("org.springframework.boot:spring-boot-starter-mail:2.7.0")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf:2.7.0")
    implementation(project(":vhr-model"))
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.0")
    testImplementation("org.springframework.amqp:spring-rabbit-test:2.4.5")
}

description = "mailserver"
